//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Activities.Extensions.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Activities.Extensions.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An activity that will delay until a specific time on certain days.
        /// </summary>
        internal static string An_activity_that_will_delay_until_a_specific_time_on_certain_days {
            get {
                return ResourceManager.GetString("An_activity_that_will_delay_until_a_specific_time_on_certain_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the Dictionary.
        /// </summary>
        internal static string ClearDictionaryDesigner_RegisterMetadata_Clears_the_Dictionary {
            get {
                return ResourceManager.GetString("ClearDictionaryDesigner_RegisterMetadata_Clears_the_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay until a specific date/time.
        /// </summary>
        internal static string DelayUntilDateTimeDesigner_RegisterMetadata_Delay_until_a_specific_date_time {
            get {
                return ResourceManager.GetString("DelayUntilDateTimeDesigner_RegisterMetadata_Delay_until_a_specific_date_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a value from the Dictionary.
        /// </summary>
        internal static string GetFromDictionaryDesigner_RegisterMetadata_Gets_a_value_from_the_Dictionary {
            get {
                return ResourceManager.GetString("GetFromDictionaryDesigner_RegisterMetadata_Gets_a_value_from_the_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invokes an Activity using WorkflowInvoker.
        /// </summary>
        internal static string Invokes_an_Activity_using_WorkflowInvoker {
            get {
                return ResourceManager.GetString("Invokes_an_Activity_using_WorkflowInvoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if a key exists in the Dictionary.
        /// </summary>
        internal static string KeyExistsInDictionaryDesigner_RegisterMetadata_Determines_if_a_key_exists_in_the_Dictionary {
            get {
                return ResourceManager.GetString("KeyExistsInDictionaryDesigner_RegisterMetadata_Determines_if_a_key_exists_in_the_" +
                        "Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads an activity from XAML.
        /// </summary>
        internal static string LoadActivityDesigner_RegisterMetadata_Loads_an_activity_from_XAML {
            get {
                return ResourceManager.GetString("LoadActivityDesigner_RegisterMetadata_Loads_an_activity_from_XAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads and invokes a workflow.
        /// </summary>
        internal static string Loads_and_invokes_a_workflow {
            get {
                return ResourceManager.GetString("Loads_and_invokes_a_workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a key from the Dictionary.
        /// </summary>
        internal static string RemoveFromDictionaryDesigner_RegisterMetadata_Removes_a_key_from_the_Dictionary {
            get {
                return ResourceManager.GetString("RemoveFromDictionaryDesigner_RegisterMetadata_Removes_a_key_from_the_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if a value exists in the dictionary.
        /// </summary>
        internal static string ValueExistsInDictionaryDesigner_RegisterMetadata_Determines_if_a_value_exists_in_the_dictionary {
            get {
                return ResourceManager.GetString("ValueExistsInDictionaryDesigner_RegisterMetadata_Determines_if_a_value_exists_in_" +
                        "the_dictionary", resourceCulture);
            }
        }
    }
}
