//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApplicationServices.Application {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitJobApplicationRequest", Namespace="http://contoso.com/contracts/hr")]
    [System.SerializableAttribute()]
    public partial class SubmitJobApplicationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid RequestIDField;
        
        private HRApplicationServices.Application.ApplicantResume ResumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((this.RequestIDField.Equals(value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public HRApplicationServices.Application.ApplicantResume Resume {
            get {
                return this.ResumeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResumeField, value) != true)) {
                    this.ResumeField = value;
                    this.RaisePropertyChanged("Resume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicantResume", Namespace="http://contoso.com/contracts/hr")]
    [System.SerializableAttribute()]
    public partial class ApplicantResume : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EducationField;
        
        private string EmailField;
        
        private string NameField;
        
        private int NumReferencesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Education {
            get {
                return this.EducationField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationField, value) != true)) {
                    this.EducationField = value;
                    this.RaisePropertyChanged("Education");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumReferences {
            get {
                return this.NumReferencesField;
            }
            set {
                if ((this.NumReferencesField.Equals(value) != true)) {
                    this.NumReferencesField = value;
                    this.RaisePropertyChanged("NumReferences");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitJobApplicationResponse", Namespace="http://contoso.com/contracts/hr")]
    [System.SerializableAttribute()]
    public partial class SubmitJobApplicationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicantNameField;
        
        private int ApplicationIDField;
        
        private string ResponseTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ApplicantName {
            get {
                return this.ApplicantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicantNameField, value) != true)) {
                    this.ApplicantNameField = value;
                    this.RaisePropertyChanged("ApplicantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponseText {
            get {
                return this.ResponseTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseTextField, value) != true)) {
                    this.ResponseTextField = value;
                    this.RaisePropertyChanged("ResponseText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumanScreeningResult", Namespace="http://contoso.com/contracts/hr")]
    [System.SerializableAttribute()]
    public partial class HumanScreeningResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AppIDField;
        
        private bool HiringApprovedField;
        
        private System.Guid RequestIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((this.AppIDField.Equals(value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool HiringApproved {
            get {
                return this.HiringApprovedField;
            }
            set {
                if ((this.HiringApprovedField.Equals(value) != true)) {
                    this.HiringApprovedField = value;
                    this.RaisePropertyChanged("HiringApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((this.RequestIDField.Equals(value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contoso.com/hr/", ConfigurationName="Application.IApplicationService")]
    public interface IApplicationService {
        
        // CODEGEN: Generating message contract since the operation SubmitJobApplication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/hr/IApplicationService/SubmitJobApplication", ReplyAction="http://contoso.com/hr/IApplicationService/SubmitJobApplicationResponse")]
        HRApplicationServices.Application.SubmitJobApplicationResponse1 SubmitJobApplication(HRApplicationServices.Application.SubmitJobApplicationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation HumanScreeningCompleted is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://contoso.com/hr/IApplicationService/HumanScreeningCompleted", ReplyAction="http://contoso.com/hr/IApplicationService/HumanScreeningCompletedResponse")]
        HRApplicationServices.Application.HumanScreeningCompletedResponse HumanScreeningCompleted(HRApplicationServices.Application.HumanScreeningCompletedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitJobApplicationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/contracts/hr", Order=0)]
        public HRApplicationServices.Application.SubmitJobApplicationRequest SubmitJobApplicationRequest;
        
        public SubmitJobApplicationRequest1() {
        }
        
        public SubmitJobApplicationRequest1(HRApplicationServices.Application.SubmitJobApplicationRequest SubmitJobApplicationRequest) {
            this.SubmitJobApplicationRequest = SubmitJobApplicationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitJobApplicationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/contracts/hr", Order=0)]
        public HRApplicationServices.Application.SubmitJobApplicationResponse SubmitJobApplicationResponse;
        
        public SubmitJobApplicationResponse1() {
        }
        
        public SubmitJobApplicationResponse1(HRApplicationServices.Application.SubmitJobApplicationResponse SubmitJobApplicationResponse) {
            this.SubmitJobApplicationResponse = SubmitJobApplicationResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HumanScreeningCompletedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://contoso.com/contracts/hr", Order=0)]
        public HRApplicationServices.Application.HumanScreeningResult HumanScreeningResult;
        
        public HumanScreeningCompletedRequest() {
        }
        
        public HumanScreeningCompletedRequest(HRApplicationServices.Application.HumanScreeningResult HumanScreeningResult) {
            this.HumanScreeningResult = HumanScreeningResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HumanScreeningCompletedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<bool> boolean;
        
        public HumanScreeningCompletedResponse() {
        }
        
        public HumanScreeningCompletedResponse(System.Nullable<bool> boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationServiceChannel : HRApplicationServices.Application.IApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationServiceClient : System.ServiceModel.ClientBase<HRApplicationServices.Application.IApplicationService>, HRApplicationServices.Application.IApplicationService {
        
        public ApplicationServiceClient() {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRApplicationServices.Application.SubmitJobApplicationResponse1 HRApplicationServices.Application.IApplicationService.SubmitJobApplication(HRApplicationServices.Application.SubmitJobApplicationRequest1 request) {
            return base.Channel.SubmitJobApplication(request);
        }
        
        public HRApplicationServices.Application.SubmitJobApplicationResponse SubmitJobApplication(HRApplicationServices.Application.SubmitJobApplicationRequest SubmitJobApplicationRequest) {
            HRApplicationServices.Application.SubmitJobApplicationRequest1 inValue = new HRApplicationServices.Application.SubmitJobApplicationRequest1();
            inValue.SubmitJobApplicationRequest = SubmitJobApplicationRequest;
            HRApplicationServices.Application.SubmitJobApplicationResponse1 retVal = ((HRApplicationServices.Application.IApplicationService)(this)).SubmitJobApplication(inValue);
            return retVal.SubmitJobApplicationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRApplicationServices.Application.HumanScreeningCompletedResponse HRApplicationServices.Application.IApplicationService.HumanScreeningCompleted(HRApplicationServices.Application.HumanScreeningCompletedRequest request) {
            return base.Channel.HumanScreeningCompleted(request);
        }
        
        public System.Nullable<bool> HumanScreeningCompleted(HRApplicationServices.Application.HumanScreeningResult HumanScreeningResult) {
            HRApplicationServices.Application.HumanScreeningCompletedRequest inValue = new HRApplicationServices.Application.HumanScreeningCompletedRequest();
            inValue.HumanScreeningResult = HumanScreeningResult;
            HRApplicationServices.Application.HumanScreeningCompletedResponse retVal = ((HRApplicationServices.Application.IApplicationService)(this)).HumanScreeningCompleted(inValue);
            return retVal.boolean;
        }
    }
}
