//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Activities.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Activities.Extensions.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one state machine is tracked, use the TrackedStateMachines collection to access the property.
        /// </summary>
        internal static string More_than_one_state_machine_is_tracked {
            get {
                return ResourceManager.GetString("More_than_one_state_machine_is_tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output argument was found.
        /// </summary>
        internal static string No_output_argument_was_found {
            get {
                return ResourceManager.GetString("No_output_argument_was_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tracking records to trace.
        /// </summary>
        internal static string No_tracking_records_to_trace {
            get {
                return ResourceManager.GetString("No_tracking_records_to_trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dictionary has not been initialized.
        /// </summary>
        internal static string The_Dictionary_has_not_been_initialized {
            get {
                return ResourceManager.GetString("The_Dictionary_has_not_been_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resume bookmark name &quot;{0}&quot; result: {1}.
        /// </summary>
        internal static string Unable_to_resume_bookmark_name {
            get {
                return ResourceManager.GetString("Unable_to_resume_bookmark_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Timeout waiting for ActivityLifecycle to complete, aborting workflow instance.
        /// </summary>
        internal static string Workflow_Timeout_ActivityLifecycle {
            get {
                return ResourceManager.GetString("Workflow_Timeout_ActivityLifecycle", resourceCulture);
            }
        }
    }
}
