//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Activities.UnitTesting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Activities.UnitTesting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action did not throw exception of type {0}..
        /// </summary>
        internal static string ActionDidNotThrow {
            get {
                return ResourceManager.GetString("ActionDidNotThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Cannot find ActivityStateRecord for Activity &quot;{1}&quot; with state &lt;{2}&gt;..
        /// </summary>
        internal static string ActivityStateRecordDoesNotExist {
            get {
                return ResourceManager.GetString("ActivityStateRecordDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Cannot find ActivityStateRecord for Activity &quot;{1}&quot; with state &lt;{2}&gt; at index &lt;{3}&gt;..
        /// </summary>
        internal static string ActivityStateRecordDoesNotExistAt {
            get {
                return ResourceManager.GetString("ActivityStateRecordDoesNotExistAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Cannot find ActivityStateRecord for Activity &quot;{1}&quot; with state &lt;{2}&gt; and argument &lt;{3}&gt; matching regular expression &lt;{4}&gt; starting at index &lt;{5}&gt;..
        /// </summary>
        internal static string ActivityStateRecordDoesNotMatchArg {
            get {
                return ResourceManager.GetString("ActivityStateRecordDoesNotMatchArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Found ActivityStateRecord for Activity &quot;{1}&quot; with state &lt;{2}&gt;..
        /// </summary>
        internal static string ActivityStateRecordExists {
            get {
                return ResourceManager.GetString("ActivityStateRecordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Cannot find ActivityStateRecord for Activity Id [{1}] with state &lt;{2}&gt;..
        /// </summary>
        internal static string ActivityStateRecordIdDoesNotExist {
            get {
                return ResourceManager.GetString("ActivityStateRecordIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Cannot find ActivityStateRecord for Activity Id [{1}] with state &lt;{2}&gt; starting at index &lt;{3}&gt;..
        /// </summary>
        internal static string ActivityStateRecordIdDoesNotExistIndex {
            get {
                return ResourceManager.GetString("ActivityStateRecordIdDoesNotExistIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AggregateException does not contain expected exception type {0} Aggregate message {1}.
        /// </summary>
        internal static string AggregateExceptionDoesNotContainExpectedException {
            get {
                return ResourceManager.GetString("AggregateExceptionDoesNotContainExpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertHelper.Throws failed. Inner exception instance of type failed. Expected type:&lt;{0}&gt;. Actual type:&lt;{1}&gt;..
        /// </summary>
        internal static string AssertCaughtExceptionInnerExceptionInstanceOfTypeFailed {
            get {
                return ResourceManager.GetString("AssertCaughtExceptionInnerExceptionInstanceOfTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertHelper.Contains failed. Value &lt;{0}&gt; was not found in collection &lt;{1}&gt;.
        /// </summary>
        internal static string ContainsValueNotFound {
            get {
                return ResourceManager.GetString("ContainsValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count must not be greater than expected.count().
        /// </summary>
        internal static string count_must_not_be_greater_than_expected_count {
            get {
                return ResourceManager.GetString("count_must_not_be_greater_than_expected_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertHelper.Throws failed. Expected exception message &lt;&quot;{0}&quot;&gt; actual message &lt;&quot;{1}&quot;&gt;.
        /// </summary>
        internal static string ExpectedExceptionMessageMismatch {
            get {
                return ResourceManager.GetString("ExpectedExceptionMessageMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If using InArguments you should not pass arguments in a dictionary..
        /// </summary>
        internal static string If_using_InArguments_you_should_not_pass_arguments_in_a_dictionary {
            get {
                return ResourceManager.GetString("If_using_InArguments_you_should_not_pass_arguments_in_a_dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.IsInstanceOfType failed.  Expected type:&lt;{0}&gt;. Actual type:&lt;{1}&gt;..
        /// </summary>
        internal static string IsInstanceOfTypeFailed {
            get {
                return ResourceManager.GetString("IsInstanceOfTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertHelper.OccursInOrder failed. Expected collection of &lt;{0}&gt; is larger than actual collection, expected &lt;{1}&gt; found &lt;{2}&gt;.
        /// </summary>
        internal static string OccursInOrderExpectedCollectionLargerThanActual {
            get {
                return ResourceManager.GetString("OccursInOrderExpectedCollectionLargerThanActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertHelper.OccursInOrder failed. Expected:&lt;{0}&gt;. Actual:&lt;{1}&gt; in collection of &lt;{2}&gt; found at index {3} expected &lt;{4}&gt; found &lt;{5}&gt;.
        /// </summary>
        internal static string OccursInOrderExpectedNotActual {
            get {
                return ResourceManager.GetString("OccursInOrderExpectedNotActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.AreEqual failed. Expected:&lt;{0}&gt;. Actual:&lt;{1}&gt;..
        /// </summary>
        internal static string OutArgAreEqualFailMsg {
            get {
                return ResourceManager.GetString("OutArgAreEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.AreNotEqual failed. Expected any value except:&lt;{0}&gt;. Actual:&lt;{1}&gt;..
        /// </summary>
        internal static string OutArgAreNotEqualFailMsg {
            get {
                return ResourceManager.GetString("OutArgAreNotEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.{0} failed.
        /// </summary>
        internal static string OutArgBoolFailMsg {
            get {
                return ResourceManager.GetString("OutArgBoolFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.AreEqualCollection failed at index {0}. Expected:&lt;{1}&gt;. Actual:&lt;{2}&gt;..
        /// </summary>
        internal static string OutArgCollectionArgEqualFailMsg {
            get {
                return ResourceManager.GetString("OutArgCollectionArgEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.{0} failed. Output does not contain an argument named &lt;{1}&gt;..
        /// </summary>
        internal static string OutArgDoesNotContain {
            get {
                return ResourceManager.GetString("OutArgDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.IsNotNull failed..
        /// </summary>
        internal static string OutArgIsNotNull {
            get {
                return ResourceManager.GetString("OutArgIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.{0} failed. {1}..
        /// </summary>
        internal static string OutArgIsNotNullInternal {
            get {
                return ResourceManager.GetString("OutArgIsNotNullInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.IsNull failed..
        /// </summary>
        internal static string OutArgIsNull {
            get {
                return ResourceManager.GetString("OutArgIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.{0} failed output is null..
        /// </summary>
        internal static string OutArgOutputIsNull {
            get {
                return ResourceManager.GetString("OutArgOutputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertOutArgument.{0} failed. Wrong type for OutArgument &lt;{1}&gt;. Expected Type: &lt;{2}&gt;. Actual Type: &lt;{3}&gt;..
        /// </summary>
        internal static string OutArgWrongType {
            get {
                return ResourceManager.GetString("OutArgWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output is null.
        /// </summary>
        internal static string OutputIsNull {
            get {
                return ResourceManager.GetString("OutputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arguments.
        /// </summary>
        internal static string parameter_arguments {
            get {
                return ResourceManager.GetString("parameter_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count must be &gt; 0.
        /// </summary>
        internal static string RecordCountInvalid {
            get {
                return ResourceManager.GetString("RecordCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. ActivityScheduledRecord for Parent Activity Id [{1}] and Child Id [{2}] not found..
        /// </summary>
        internal static string ScheduledIdRecordNotFound {
            get {
                return ResourceManager.GetString("ScheduledIdRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. ActivityScheduledRecord for Parent Activity  Id [{1}] and Child Id [{2}] not found..
        /// </summary>
        internal static string ScheduledRecordIdNotFound {
            get {
                return ResourceManager.GetString("ScheduledRecordIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. ActivityScheduledRecord for Parent Activity &quot;{1}&quot; and Child &quot;{2}&quot; not found..
        /// </summary>
        internal static string ScheduledRecordNotFound {
            get {
                return ResourceManager.GetString("ScheduledRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. For Activity Id [{1}] with state &lt;{2}&gt; expected a count of &lt;{3}&gt; actual count was &lt;{4}&gt;..
        /// </summary>
        internal static string stringStateRecordDoesNotExistCount {
            get {
                return ResourceManager.GetString("stringStateRecordDoesNotExistCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Cannot find TrackingRecord with predicate..
        /// </summary>
        internal static string TrackingRecordDoesNotExist {
            get {
                return ResourceManager.GetString("TrackingRecordDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. ActivityStateRecord for Activity &quot;{1}&quot; with state &lt;{2}&gt; was found at index &lt;{3}&gt; and did not occur before Activity &quot;{4}&quot; found at index &lt;{5}&gt;..
        /// </summary>
        internal static string TrackingRecordNotBefore {
            get {
                return ResourceManager.GetString("TrackingRecordNotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. ActivityStateRecord for Activity &quot;{1}&quot; with state &lt;{2}&gt; was found at index &lt;{3}&gt; and did not occur before Activity &quot;{4}&quot; found at index &lt;{5}&gt;..
        /// </summary>
        internal static string TrackingRecordNotBeforeState {
            get {
                return ResourceManager.GetString("TrackingRecordNotBeforeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. ActivityStateRecord for Activity &quot;{1}&quot; with state &lt;{2}&gt; not found..
        /// </summary>
        internal static string TrackingRecordNotFound {
            get {
                return ResourceManager.GetString("TrackingRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.Output is not set yet.
        /// </summary>
        internal static string WorkflowApplicationTest_CheckResultsOutput_Results_Output_is_not_set_yet {
            get {
                return ResourceManager.GetString("WorkflowApplicationTest_CheckResultsOutput_Results_Output_is_not_set_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Cannot find WorkflowInstanceRecord for with state &lt;{1}&gt;..
        /// </summary>
        internal static string WorkflowInstanceStateNotFound {
            get {
                return ResourceManager.GetString("WorkflowInstanceStateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssertTracking.{0} failed. Cannot find WorkflowInstanceRecord for with state &lt;{1}&gt; starting at index &lt;{2}&gt;..
        /// </summary>
        internal static string WorkflowInstanceStateNotFoundIndex {
            get {
                return ResourceManager.GetString("WorkflowInstanceStateNotFoundIndex", resourceCulture);
            }
        }
    }
}
