//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamlAssemblyResolutionWeb.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResolutionInfo", Namespace="http://schemas.datacontract.org/2004/07/XamlAssemblyResolutionWeb")]
    [System.SerializableAttribute()]
    public partial class ResolutionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ActivityLibrary1.AssemblyResolutionInfo ActivityAssemblyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ActivityLibrary1.AssemblyResolutionInfo WebAssemblyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ActivityLibrary1.AssemblyResolutionInfo ActivityAssembly {
            get {
                return this.ActivityAssemblyField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityAssemblyField, value) != true)) {
                    this.ActivityAssemblyField = value;
                    this.RaisePropertyChanged("ActivityAssembly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ActivityLibrary1.AssemblyResolutionInfo WebAssembly {
            get {
                return this.WebAssemblyField;
            }
            set {
                if ((object.ReferenceEquals(this.WebAssemblyField, value) != true)) {
                    this.WebAssemblyField = value;
                    this.RaisePropertyChanged("WebAssembly");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAssemblyNames", ReplyAction="http://tempuri.org/IService/GetAssemblyNamesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetAssemblyNameResult")]
        XamlAssemblyResolutionWeb.ServiceReference.ResolutionInfo GetAssemblyNames();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : XamlAssemblyResolutionWeb.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<XamlAssemblyResolutionWeb.ServiceReference.IService>, XamlAssemblyResolutionWeb.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XamlAssemblyResolutionWeb.ServiceReference.ResolutionInfo GetAssemblyNames() {
            return base.Channel.GetAssemblyNames();
        }
    }
}
