//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Activities.Extensions.Tests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        // CODEGEN: Generating message contract since the operation T6 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/T6")]
        void T6(Microsoft.Activities.Extensions.Tests.ServiceReference1.T6 request);
        
        // CODEGEN: Generating message contract since the operation T2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/T2")]
        void T2(Microsoft.Activities.Extensions.Tests.ServiceReference1.T2 request);
        
        // CODEGEN: Generating message contract since the operation T3 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/T3")]
        void T3(Microsoft.Activities.Extensions.Tests.ServiceReference1.T3 request);
        
        // CODEGEN: Generating message contract since the operation T7 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/T7")]
        void T7(Microsoft.Activities.Extensions.Tests.ServiceReference1.T7 request);
        
        // CODEGEN: Generating message contract since the operation T5 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/T5")]
        void T5(Microsoft.Activities.Extensions.Tests.ServiceReference1.T5 request);
        
        // CODEGEN: Generating message contract since the operation T4 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/T4")]
        void T4(Microsoft.Activities.Extensions.Tests.ServiceReference1.T4 request);
        
        // CODEGEN: Generating message contract since the operation T1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/T1", ReplyAction="http://tempuri.org/IService/T1Response")]
        Microsoft.Activities.Extensions.Tests.ServiceReference1.T1Response T1(Microsoft.Activities.Extensions.Tests.ServiceReference1.T1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class T6 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public T6() {
        }
        
        public T6(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class T2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public T2() {
        }
        
        public T2(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class T3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public T3() {
        }
        
        public T3(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class T7 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public T7() {
        }
        
        public T7(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class T5 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public T5() {
        }
        
        public T5(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class T4 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public T4() {
        }
        
        public T4(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class T1Request {
        
        public T1Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class T1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public T1Response() {
        }
        
        public T1Response(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Microsoft.Activities.Extensions.Tests.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Microsoft.Activities.Extensions.Tests.ServiceReference1.IService>, Microsoft.Activities.Extensions.Tests.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Microsoft.Activities.Extensions.Tests.ServiceReference1.IService.T6(Microsoft.Activities.Extensions.Tests.ServiceReference1.T6 request) {
            base.Channel.T6(request);
        }
        
        public void T6(System.Nullable<System.Guid> guid) {
            Microsoft.Activities.Extensions.Tests.ServiceReference1.T6 inValue = new Microsoft.Activities.Extensions.Tests.ServiceReference1.T6();
            inValue.guid = guid;
            ((Microsoft.Activities.Extensions.Tests.ServiceReference1.IService)(this)).T6(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Microsoft.Activities.Extensions.Tests.ServiceReference1.IService.T2(Microsoft.Activities.Extensions.Tests.ServiceReference1.T2 request) {
            base.Channel.T2(request);
        }
        
        public void T2(System.Nullable<System.Guid> guid) {
            Microsoft.Activities.Extensions.Tests.ServiceReference1.T2 inValue = new Microsoft.Activities.Extensions.Tests.ServiceReference1.T2();
            inValue.guid = guid;
            ((Microsoft.Activities.Extensions.Tests.ServiceReference1.IService)(this)).T2(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Microsoft.Activities.Extensions.Tests.ServiceReference1.IService.T3(Microsoft.Activities.Extensions.Tests.ServiceReference1.T3 request) {
            base.Channel.T3(request);
        }
        
        public void T3(System.Nullable<System.Guid> guid) {
            Microsoft.Activities.Extensions.Tests.ServiceReference1.T3 inValue = new Microsoft.Activities.Extensions.Tests.ServiceReference1.T3();
            inValue.guid = guid;
            ((Microsoft.Activities.Extensions.Tests.ServiceReference1.IService)(this)).T3(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Microsoft.Activities.Extensions.Tests.ServiceReference1.IService.T7(Microsoft.Activities.Extensions.Tests.ServiceReference1.T7 request) {
            base.Channel.T7(request);
        }
        
        public void T7(System.Nullable<System.Guid> guid) {
            Microsoft.Activities.Extensions.Tests.ServiceReference1.T7 inValue = new Microsoft.Activities.Extensions.Tests.ServiceReference1.T7();
            inValue.guid = guid;
            ((Microsoft.Activities.Extensions.Tests.ServiceReference1.IService)(this)).T7(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Microsoft.Activities.Extensions.Tests.ServiceReference1.IService.T5(Microsoft.Activities.Extensions.Tests.ServiceReference1.T5 request) {
            base.Channel.T5(request);
        }
        
        public void T5(System.Nullable<System.Guid> guid) {
            Microsoft.Activities.Extensions.Tests.ServiceReference1.T5 inValue = new Microsoft.Activities.Extensions.Tests.ServiceReference1.T5();
            inValue.guid = guid;
            ((Microsoft.Activities.Extensions.Tests.ServiceReference1.IService)(this)).T5(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Microsoft.Activities.Extensions.Tests.ServiceReference1.IService.T4(Microsoft.Activities.Extensions.Tests.ServiceReference1.T4 request) {
            base.Channel.T4(request);
        }
        
        public void T4(System.Nullable<System.Guid> guid) {
            Microsoft.Activities.Extensions.Tests.ServiceReference1.T4 inValue = new Microsoft.Activities.Extensions.Tests.ServiceReference1.T4();
            inValue.guid = guid;
            ((Microsoft.Activities.Extensions.Tests.ServiceReference1.IService)(this)).T4(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microsoft.Activities.Extensions.Tests.ServiceReference1.T1Response Microsoft.Activities.Extensions.Tests.ServiceReference1.IService.T1(Microsoft.Activities.Extensions.Tests.ServiceReference1.T1Request request) {
            return base.Channel.T1(request);
        }
        
        public System.Nullable<System.Guid> T1() {
            Microsoft.Activities.Extensions.Tests.ServiceReference1.T1Request inValue = new Microsoft.Activities.Extensions.Tests.ServiceReference1.T1Request();
            Microsoft.Activities.Extensions.Tests.ServiceReference1.T1Response retVal = ((Microsoft.Activities.Extensions.Tests.ServiceReference1.IService)(this)).T1(inValue);
            return retVal.guid;
        }
    }
}
